# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 492f7878ded7fd11bd625cd282b489cf79c15e8822eb7edc04cb02c499e8f794205ce98efcd817af33969adf42314878aa41ca227ba5f54868e2ee12d9fe22f6

test:
  secret_key_base: e61fadb2998e2423d0b7b2687a9bbbdd39c7fd94ef60765527abac009390aac940d90822dd3982d923b29c4942dd559a0d6837b3faadae0efe537414333524b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
